triggers:
  - name: triggertest3
    type: trigger
    version:
      counter: 275
      
  - name: triggertest4
    type: trigger
    version:
      counter: 430

  - name: triggertest5
    type: trigger
    version:
      counter: 0
