jobs:
  - name: runShk7
    type: runSh
  #  serial: true
    steps:
      - IN: sample-script-3
     # - IN: env
      - IN: triggertest4
      - TASK:
        - script: ./IN/sample-script-3/gitRepo/echo.sh
        - script: pwd
        - script: ls
        - script: export FOO=bar
        - script: export FOO1=bar1
        - script: echo $FOO && echo $FOO1
        # - script: "node --version"
        # - script: echo "$foo"
        # - script: echo "$n1"
        # - script: echo 'new'
        #- script: "sudo apt-get install tree"
    on_success:
      #- uname -a
      - NOTIFY: myEmail2
      - NOTIFY: mySlack2
      - script: echo 'infra test'
      - script: echo 'newtesting success'
     # - script: build/IN/sample-script-3/gitRepo/echo.sh
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
      - NOTIFY: mySlack2
      - NOTIFY: myEmail2
      
  - name: runShk8
    type: runSh
   #  serial: true
    steps:
      - IN: sample-script-4
      - IN: triggertest4
      - TASK:
        - script: ./IN/sample-script-4/gitRepo/echo.sh
  
 
